### ISSUE TITLE
Add DaemonSet as second deployment option

### ISSUE THREAD

**Issue by fahlke** [richstokes/k8s-fah#1]
In order to fully utilize a cluster without the need to scale a deployment (manually) I would suggest  to add the option of a deployment via DaemonSet. This would run FaH on all nodes on the cluster.

~I'm currently setting up my Raspberry Pi experimental cluster and will implement and test this addition.~
*Edit:* Just figured out, that FaH will not run on ARM. So I have (at the moment) no cluster available for testing and implementing.

Ideas so far:
- [x] selection of nodes via `nodeSelector`
- [x] sane default resource limits to not over-utilize a cluster

**Comment by richstokes** [comment]
Thanks for the suggestions @fahlke -- just added a DaemonSet option and updated the README with instructions.

I feel like the default resource limit (1 CPU core) is pretty sane and easy to adjust as needed.

It may be worth pinging the folding guys and seeing if there's a build for ARM on the cards.

**Comment by fahlke** [comment]
LGTM (sadly, as said, I cannot test right now)

Will give a brief update here, if I can get my fingers on a cluster for testing.
