### ISSUE TITLE
StatefulSets & Persistent Volume Claims

### ISSUE THREAD

**Issue by farazmujtaba** [richstokes/k8s-fah#12]
I have found using Persistent Volume Claim mounts are helpful for FAH on K8s as it allows the container to checkpoint work (default is every 15m) and recover state for an existing assignment if the container is terminated. 

To do this I have implement the StatefulSet deployment pattern, in order for each container to have its own unique PVC (in a deployment pattern they would all share the same PVC). I am mounting the PVC at `mountPath: /var/lib/fahclient `. I don't know how much storage is expected/ required by FAH, but I can look into the average utilization on my cluster. 

Happy to share my YAML as an example but I have forked a bit for my environment on Google Cloud/Google Kubernetes Engine.

**Comment by richstokes** [comment]
Hi, thanks the the suggestions - all good ideas. That said, I feel it’s better to leave the deployments in this repo stateless. 

I’d rather not add storage requirements, as this could complicate things, especially for folks who run a large number of replicas.
