### ISSUE TITLE
Any chance of an arm version

### ISSUE THREAD

**Issue by 2fst4u** [richstokes/k8s-fah#14]
Your image looks awesome, I'm really keen to try this on my cluster but I only have raspberry pis so far. Any chance you'd be able to release an arm (or arm64 specifically) image?

**Comment by richstokes** [comment]
There is a chance, yea! Just not sure how I'd build/test it since I dont have any ARM devices..

If you like, feel free to create a PR - I'd suggest a new dockerfile and yaml for running it

**Comment by 2fst4u** [comment]
Oh waaaay beyond my capabilities, I've never contributed to a repo before. No rush though if someone else is keen to.

**Comment by skandix** [comment]
I might create a raspi cluster over the new year, I'll keep this in the back of my head :). but shouldn't be too much of a big change I think 🤔

**Comment by richstokes** [comment]
Yeah I think it would be pretty straightforward to create the image, it's just needing some hardware to build/test it on. I tried emulating a R-Pi but it was just way too slow to work with :P

**Comment by kaovilai** [comment]
@2fst4u please help test if this works. I do not currently have arm64 cluster on hand. But podman says it works.

**Comment by kaovilai** [comment]
@skandix let me know if your awesome raspi cluster work.

@richstokes you don't actually need hardware, you can emulate it to build on your favorite fast machine.. or as in the https://github.com/richstokes/k8s-fah/pull/17 case, just using Github Actions.

**Comment by 2fst4u** [comment]
> @2fst4u please help test if this works. I do not currently have arm64 cluster on hand. But podman says it works.

I will give it a try next week as I'm currently on holiday away from my system. Looks promising!

**Comment by kaovilai** [comment]
Heh. Added E2E tests here https://github.com/richstokes/k8s-fah/pull/18.

[Circle CI](https://app.circleci.com/pipelines/github/kaovilai/k8s-fah/18/workflows/07193bd0-a1b4-4f83-ba76-fbccd45dc0e8/jobs/17) | [Travis](https://app.travis-ci.com/github/kaovilai/k8s-fah/builds/256170733) shows ARM64 working on ARM64 [kind](https://kind.sigs.k8s.io/) cluster.
