### ISSUE TITLE
Minimum CPU?

### ISSUE THREAD

**Issue by cgetzen** [richstokes/k8s-fah#4]
Hi! I'd love to eval this for a large org. Do you know what the minimum viable CPU is? Thanks!

**Comment by richstokes** [comment]
I'm not sure if Folding has any time limit on workunits they send. You wouldnt want to set the CPU so low that it takes too long to complete the unit and times out basically.

I would suggest setting it to a quarter of one CPU core (250m) and work up from there.

**Comment by cgetzen** [comment]
Thanks :)
