### ISSUE TITLE
Resource limit memory too low

### ISSUE THREAD

**Issue by Ka1wa** [richstokes/k8s-fah#9]
Hi,

First of all thanks for creating this project, I've used it to quickly donate some of my spare CPU power. However I just wanted to let you know that the 256Mi memory limit in your configuration files is too low and that pods will get OOMKilled.

Ex:
```
NAME        CPU(cores)   MEMORY(bytes)
fah-5j7bg   1001m        48Mi
fah-plvwd   1001m        308Mi
fah-wh5tg   999m         110Mi
```

So far I haven't seen it exceed 512Mi though, maybe that's a better limit?

Thanks for your work!

**Comment by richstokes** [comment]
Thanks for the feedback - I have updated the memory limit to 512
